name: ASP.NET CI/CD

on:
  push:
    branches: [ "main" ]

env:
  DOTNET_VERSION: '8.0.x'
  BUILD_CONFIGURATION: 'Release'

jobs:

  # =========================
  # 🧪 CI: BUILD + TEST
  # =========================
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 📦 Restore
        run: dotnet restore

      - name: 🔨 Build
        run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: 🧪 Test
        run: dotnet test --no-build

      - name: 📤 Publish
        run: dotnet publish -c ${{ env.BUILD_CONFIGURATION }} -o ./publish

      - name: 💾 Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./publish


  # =========================
  # 🚀 CD: DEPLOY
  # =========================
  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: 📥 Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: 🚀 Deploy local
        run: |
          mkdir -p /var/www/app
          cp -r * /var/www/app

      - name: 🔄 Restart app (Linux)
        run: |
          sudo systemctl restart myapp || echo "No service found"